import { ReactNode } from 'react';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.scss';

import Footer from '@/components/Footer';
import Header from '@/components/Header';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const interFont = Inter({
    subsets: ['latin'],
    weight: ['400', '700'],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={interFont.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
