name: Playwright Tests
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TEST_CHECK_ENV: test
      NEWS_API_URL: ${{ secrets.NEWS_API_URL }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Clean .next folder
        run: rm -rf .next
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
